# Generated by Django 3.2 on 2021-04-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('change_title', 'Can change title'),)},
        ),
    ]
