# Generated by Django 3.2 on 2021-04-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210424_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_request',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookinst', to='catalog.bookinstance'),
        ),
    ]
